### PR TITLE
fix script generation to not comment out the first line

### PR DESCRIPTION
**Pull request by Ukalnins**
Seems that noone is using the deadlock timer.

### CODE REVIEW

**Comment by gabebear** [comment]
What versions of Xcode has this been tested in? The last time this escaping was tweaked was because of a problem parsing it in Xcode 10 https://github.com/ios-control/ios-deploy/commit/69b24ca5e8e27fb6f2c2b6831004043b663ee0d5.

Since this has broken on Xcode versions before ideally want to test at least:
 - Xcode11 on Mojave
 - Xcode12 on Catalina
 - Xcode12 on Big Sur

I don't have any Mojave Macs anymore, but could check the others if you haven't.

**Comment by gabebear** [comment]
The multi-nested escaping makes my head hurt.
 - XML .pbxproj file containing:
   - bash script containing:
      - both double-quoted and single-quoted strings containing:
         - backslash escaped characters containing:
            - ObjC code containing:
               - Python code.

**Comment by Ukalnins** [comment]
I'm running Xcode-12 on Catalina, so it works on that. I can check Big Sur on monday. 

I would be against retiring the separate python script as it simplifies development of the script. Though I agree that the number of nested escaping is complicated and hacky as hell. Maybe splitting it out generation as a separate script help?

**Comment by gabebear** [comment]
Hmmm... what about switching to [raw-literal-strings](https://en.cppreference.com/w/cpp/language/string_literal)? C++11 supports them in this format:
```
const char* python_script = R"prx63htg4(
import time
import os
import sys
import shlex
import lldb

blah blah...
)prx63htg4";
```

**Comment by gabebear** [comment]
Going to go ahead and merge rather than overthink it

**Comment by Ukalnins** [comment]
Hi, sorry, got sick and forgot about this PL. 

I really like your idea, we can just put it in a separate cpp file. I'll create a PL when I have the time.

**Comment by gabebear** [comment]
No worries, thanks for all the hard work!

**Pull request merged**
