### PR TITLE
fix: use semver to properly validate versions

### PR DESCRIPTION
**Pull request by rdeva31**
Otherwise "10.0" is deemed to be smaller than "7.0", resulting in
strange install errors.

Fixes:
image

### CODE REVIEW

**Comment by rdeva31** [comment]
```
Error: Cannot find module 'semver'
```
wtf I have the dependancy: https://github.com/rdeva31/ios-deploy/blob/684665d50a30e58f56a046b837a05f140e87c313/package.json#L18

Haalp I'm not a JS developer.

cc @shazron

**Comment by shazron** [comment]
Looks like a chicken and egg problem -- semver is installed during `npm install`, but you are requiring it in the `preinstall` script `check_reqs.js` (see package.json)

**Comment by shazron** [comment]
Might have found a solution. Please enable this so I can push to your branch: https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

The commit: https://github.com/ios-control/ios-deploy/commit/fe13efab21d30b1853cda06194009ce7e4cedb3f

**Comment by gabebear** [comment]
El Capitan is 4+ years old now... probably best to remove the warning message at this point.

**Comment by gabebear** [comment]
Closing in favor of #428 428

**Pull request closed without merging**
