### PR TITLE
Mention MacPorts in readme

### PR DESCRIPTION
**Pull request by amake**
ios-deploy is also available in MacPorts.

### CODE REVIEW

**Comment by gabebear** [comment]
I am not aware of how MacPorts gets updated. Could you give an overview of how people get specific versions of ios-deploy using MacPorts?

We post updates to both Homebrew and npmjs via our releasing procedure. https://github.com/ios-control/ios-deploy/blob/master/RELEASING.md

I'm a bit hesitant to support another way of installing... We already get a lot of questions about problems with specific installation methods.

**Comment by amake** [comment]
> I am not aware of how MacPorts gets updated. Could you give an overview of how people get specific versions of ios-deploy using MacPorts? (the code at HEAD in this repo is not always 100% stable)

It depends on the maintainer, but in general only releases (tags) are made available, and only on a manual basis: there is no auto-update or anything, so (in theory) there is always a human vetting things.

> I'm very hesitant to support another way of installing... We already get a lot of questions about problems with specific installation methods that are not related to this project.

If your policy is "we officially support and manage distribution to package managers X and Y, and we don't want to advertise other package managers" then that totally makes sense; in that case maybe mentioning MacPorts is not a good idea.

Many projects don't officially involve themselves in distribution, leaving things entirely to volunteers downstream. In those cases, I find that the upstream maintainers are happy to learn about and advertise availability in various packaging managers (I don't think they consider such advertisement to be a vow of "support").

But I appreciate that your policy may differ. If you prefer not to advertise MacPorts availability then please do feel free to reject this PR.

**Comment by gabebear** [comment]
I don't think we will take-on releasing on MacPorts.

We only took on releasing on Homebrew ~1year ago because there was no Homebrew maintainer and ios-deploy was in danger of being de-listed from Homebrew if nobody had stepped up to maintain it. We had also started getting a lot of questions about npm.js that were unrelated to our project(We have been releasing on npm.js for over 8 years).

**Comment by amake** [comment]
I was not asking you to take responsibility for releasing to MacPorts, only to notify users of availability in MacPorts.

**Comment by gabebear** [comment]
If we document the command then we are taking-on the work to check that it continues to work as expected.

**Pull request closed without merging**
