### PR TITLE
Add back to code for --nolldb (-N)

### PR DESCRIPTION
**Pull request by LinusU**
This code was accidentally removed by a recent merge commit...

### CODE REVIEW

**Comment by shazron** [comment]
Can this be changed so it is merged into master? I'm removing the 1.x branch (and working off master as the trunk now) because it's causing confusion... case in point, this feature is not in master.

**Comment by shazron** [comment]
I would like to put out a 1.9.3 patch release soon

**Comment by shazron** [comment]
I'll get this merged to master, no worries

**Comment by shazron** [comment]
Merging to 1.x, then I will cherry-pick

**Comment by shazron** [comment]
1.9.3 published with this fix: https://github.com/ios-control/ios-deploy/releases/tag/1.9.3

**Comment by LinusU** [comment]
Awesome, thanks 🙌

**Pull request merged**
