### PR TITLE
Add -k/--key option. Allow getting more properties of the app

### PR DESCRIPTION
**Pull request by ryanluoo**
Now by using `-B` and `-j` options together, we can get some basic properties of the app. Like `CFBundleVersion`. 

But actually more properties could be output by passing the corresponding keys. 
> We can find all the existing keys in Apple's [doc](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Introduction/Introduction.html#//apple_ref/doc/uid/TP40009248-SW1)

So I add a new option, allowing people to get more properties. If multiple keys are needed, we can join them by '&'

For example, if we need  `UIFileSharingEnabled`, `CFBundleExecutable`, `CFBundlePackageType` of the installed app. 
>  `UIFileSharingEnabled` specifies whether the app shares files through iTunes
`CFBundleExecutable` identifies the name of the bundle’s main executable file
`CFBundlePackageType` identifies the type of the bundle and is analogous to the Mac OS 9 file type code

We can use the command :
`ios-deploy -B -j  --key=UIFileSharingEnabled&CFBundleExecutable&CFBundlePackageType`

Part of output:
```
"com.kingsoft.www.office.wpsoffice" : {
    "CFBundleShortVersionString" : "11.3.1",
    "CFBundleIdentifier" : "com.kingsoft.www.office.wpsoffice",
    "UIFileSharingEnabled" : true,
    "CFBundleDisplayName" : "WPS Office",
    "CFBundleName" : "WPS Office",
    "CFBundleExecutable" : "wpsoffice",
    "CFBundlePackageType" : "APPL",
    "CFBundleVersion" : "11.3.191809"
  },
```

### CODE REVIEW

**Comment by ryanluoo** [comment]
Also revise the error message. Seems we missed some required options before
```
        on_error(@"One of -[b|c|o|l|w|D|R|X|e|B|C|9|] is required to proceed!");
```

**Comment by ryanluoo** [comment]
May I ask how often did you release a new official version to HomeBrew ? 
My project is relying on `ios-deploy` now . Really appreciate it if I can experience the new feature from the HomeBrew stable release.

**Comment by ivanhernandez13** [comment]
Thanks for the PR! Will try to make some time today to take a look.

As for release schedule, it's pretty much ad-hoc. We haven't done a release in a while so I can get a new release going after this PR lands.

**Review by Indo1x — COMMENTED** [review]
H

**Pull request merged**
