### PR TITLE
Add ability to inject arbitrary environment variables

### PR DESCRIPTION
**Pull request by palmerc**
Sometimes you need to pass environment variables to the remote debugging session just like Xcode. I added the ability to do this.

### CODE REVIEW

**Comment by phildow** [comment]
Would love to see this merged into master. Thanks @palmerc!

**Comment by pachoo** [comment]
Agreed.  I've tried starting ios-deploy in the `-n` mode, then manually setting the target env-vars, then running but no love.  It seems having them added to the launch info is the trick.

**Comment by palmerc** [comment]
@shazron this seems like something I should be able to get on master. Any particular reason you can't accept the PR?

**Comment by shazron** [comment]
No reason, I haven't gotten around to testing the PR. Testing now.

**Comment by palmerc** [comment]
@shazron I think that it should match your requested changes now.

**Comment by shazron** [comment]
Tip for next time - don't squash your changes. It makes it easier for me to review any new changes since I last re-tested. If squashed, I would have to re-test the whole thing again if I doubt its veracity, but in this case through visual inspection from the previous it looks fine. GH has a way to squash it neatly when I merge it in.

**Pull request merged**
